### ISSUE TITLE
Invalid IPv6 URL

### ISSUE THREAD

**Issue by tombeteende** [bruin-data/ingestr#11] opened 2024-03-04 09:38 UTC
I get an `Invalid IPv6 URL` when using a valid Postgres URL. Any idea how to bypass it?

The error stems from the`urllib` package

**Comment by karakanb** [comment] 2024-03-04 12:12
thanks a lot for the report, do you happen to have an example URI without any sensitive data in it? I'd love to be able to reproduce it and see what happens.

**Comment by karakanb** [comment] 2024-12-20 09:03
A lot has changed since the first version of ingestr, and since we were not able to reproduce this issue even through various postgres deployments we had, I'll have to close it. Please feel free to reopen the issue if the issue persists, and it'd be great if you could share more instructions for reproduction.

**Closed by karakanb** 2024-12-20 09:03 UTC
