### ISSUE TITLE
Snowflake: error when your password contains the character "@"?

### ISSUE THREAD

**Issue by DrAlexSanz** [bruin-data/ingestr#15] opened 2024-03-15 11:50 UTC
Hi,

I wanted to try ingestr using snowflake because it looks really cool. I was trying to find the connection part in the repository but I didn't manage, so I haven't discarded that I am the one causing the error. However, when I connect to snowflake using sqlalchemy, I have no issues.

I managed to write the input following the documentation but if the password contains the character "@", it throws a 403 error. My understanding is that when ingestr parses the connection string, it locates only the first "@".

From the docs, the snowflake connection should be formed following this format:

`snowflake://user:password@account/dbname?warehouse=COMPUTE_WH`

so ingestr gets confused when the password has this structure:

`snowflake://user:first_half_of_password@second_half_of_password@account/dbname?warehouse=COMPUTE_WH` because the error says: Failed to connect to DB: second_half_of_password@my_account.snowflakecomputing.com:443. Bad request; operation not supported.       
(Background on this error at: https://sqlalche.me/e/14/4xp6)

This is the full command that I input:
ingestr ingest --source-uri "snowflake://user:first_half_of_password@second_half_of_password@my_account/my_db?warehouse=my_wh"
--source-table "my_schema.INGESTER_SRC"
--dest-uri "snowflake://user:first_half_of_password@second_half_of_password@my_account/my_db?warehouse=my_wh"
--dest-table "my_schema.INGESTER_DEST"

When I run it, I see ingestr asking if I would like to continue, so that part is ok.

I understand that you are under no obligation to fix it or to reply to this issue, just reporting it because I would like to use ingestr.

Thank you.
A.

**Comment by karakanb** [comment] 2024-03-17 20:58
I'll definitely take a look at this and fix it, thanks a lot for the report.

**Comment by karakanb** [comment] 2024-03-27 15:00
yeah, that seems to be the case, because apparently that seems to be an invalid URI structure. do you think that's a good enough fix or would you expect ingestr to handle non-standard URIs like that?

**Comment by karakanb** [comment] 2024-04-24 22:15
I have decided to close this issue since the URI format doesn't conform the standards. I don't have a very strong opinion on this, but I believe keeping the expected behavior around the standard seems more reasonable for now, happy to change my mind if someone else has a different perspective on this.

**Closed by karakanb** 2024-04-24 22:15 UTC
